server {
    server_name flag-analysis.fteet.ai;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/flag-analysis.fteet.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flag-analysis.fteet.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # 🚀 Public assets (images / videos)
    location /public/ {
        alias /var/lib/docker/volumes/nextjs_public/_data/;

        sendfile on;
        open_file_cache max=20000 inactive=60s;
        open_file_cache_valid 120s;

        add_header Accept-Ranges bytes;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Next.js server (HTML + API only)
    location / {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:3127;
    }

}

server {
    if ($host = flag-analysis.fteet.ai) {
        return 301 https://$host$request_uri;
    }
    # listen 80;
    server_name flag-analysis.fteet.ai;
    return 404;
}